version: "3.9"

services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.prod
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - static-data:/vol/static
    depends_on:
      - api

  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    command: npm start
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api

  api:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./api
    env_file:
      - ./config/envFiles/django/prod/.env
    command: ./docker-entrypoint-prod.sh
    volumes:
      - static-data:/usr/src/app/vol
    ports:
      - "8000:8000"
    depends_on:
      - db

  celery:
    build:
      dockerfile: Dockerfile
      context: ./api
    env_file:
      - ./config/envFiles/django/prod/.env
    command: celery -A config worker -l info
    depends_on:
      - db
      - smtp4dev
      - redis

  celery-beat:
    build:
      dockerfile: Dockerfile
      context: ./api
    env_file:
      - ./config/envFiles/django/prod/.env
    command: celery -A config beat -l info
    depends_on:
      - db
      - smtp4dev
      - redis

  celery-flower:
    build:
      dockerfile: Dockerfile
      context: ./api
    env_file:
      - ./config/envFiles/django/prod/.env
    command: celery -A config flower --basic_auth=${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}
    ports:
      - "5555:5555"
    depends_on:
      - db
      - smtp4dev
      - redis

  db:
    restart: always
    image: postgres:13-alpine
    env_file:
      - ./config/envFiles/postgres/prod/.env
    ports:
      - "${SERVER_PORT}:${DB_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data

  smtp4dev:
    image: rnwood/smtp4dev:3.1.3-ci20211206101
    restart: always
    ports:
      - "1025:80"
      - "2525:25"
      - "143:143"
    volumes:
      - smtp4dev-data:/smtp4dev

  redis:
    image: redis:alpine3.15
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata:
  static-data:
  smtp4dev-data:
