version: "3.9"

services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.prod
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - static-data:/vol/static
      - ./client/dist:/usr/share/nginx/html
    depends_on:
      - api

  api:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./api
    env_file:
      - ./config/env/django/prod/.env
    command: ./docker-entrypoint-prod.sh
    volumes:
      - static-data:/usr/src/app/vol
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    restart: always
    image: postgres:13-alpine
    env_file:
      - ./config/env/postgres/prod/.env
    ports:
      - ${SERVER_PORT}:${DB_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  static-data:
