version: "3.9"

services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./api/vol:/vol/static
    depends_on:
      - client
      - api

  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    env_file:
      - ./config/env/nginx/develop/.env
    volumes:
      - /client/node_modules
      - ./client:/usr/src/app
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api

  api:
    build:
      dockerfile: Dockerfile
      context: ./api
    env_file:
      - ./config/env/django/develop/.env
    volumes:
      - ./api:/usr/src/app
    command: ./docker-entrypoint-dev.sh
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    env_file:
      - ./config/env/postgres/develop/.env
    ports:
      - 5001:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  static-data:
