version: "3.9"

services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.prod
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - static-data:/vol/static
      - ./client/dist:/usr/share/nginx/html
    depends_on:
      - api

  api:
    build:
      dockerfile: Dockerfile
      context: ./api
    environment:
      - SECRET_KEY=devsecretkey
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
      - DB_PORT=5432
    command: ./docker-entrypoint-prod.sh
    volumes:
      - static-data:/usr/src/app/vol
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
    ports:
      - 5001:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  static-data:
