# Generated by Django 4.0.2 on 2022-04-09 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likeditem',
            options={'ordering': ('object_id',)},
        ),
    ]
