FROM nginx:1.20.2-alpine
COPY ./default-prod-ssl.conf /etc/nginx/conf.d/default.conf
COPY ./uwsgi_params /etc/nginx/uwsgi_params
COPY ./docker-entrypoint-prod.sh /docker-entrypoint.sh

RUN mkdir -p /vol/static && \
    chmod 755 /vol/static

RUN chmod +x /docker-entrypoint.sh

ARG APP_URL
RUN sed -i "s|\$APP_URL|$APP_URL|g" /etc/nginx/conf.d/default.conf

CMD ["/docker-entrypoint.sh"]
