# Generated by Django 4.0.2 on 2022-04-09 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='register_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
