# Generated by Django 4.0.2 on 2022-02-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='attachment2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
