# Generated by Django 4.0.2 on 2022-04-09 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_register_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='register_code',
            new_name='register_token',
        ),
    ]
