# Generated by Django 4.0.2 on 2022-04-09 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_register_code_user_register_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='register_token',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
